<a href="https://colab.research.google.com/github/anweshaban21/torchsync/blob/main/Initial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.6.0+cu124


In [4]:
if torch.cuda.is_available():
  print("cuda is available")
else:
  print("cuda is not available")

cuda is not available


Creating a tensor


In [6]:
a=torch.empty(3,3)

In [7]:
type(a)

torch.Tensor

In [8]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.manual_seed(11)  #for generating random values which would be same for each time(reproducibility)
torch.rand(2,3)

tensor([[0.1490, 0.4866, 0.9857],
        [0.1684, 0.5839, 0.6936]])

In [11]:
torch.eye(5) #Identity matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [12]:
torch.full((3,3),4)

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

In [13]:
torch.tensor([1.0,2.2,3.3],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)